server:
  port: 3344
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baybay24/springcloud-config
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  instance:
    hostname: springcloud-config
  client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka